packages <- c("MASS","e1071","caret","neuralnet","glmnet","mltools","data.table","janitor", "corrplot","dplyr","jtools","crs","earth")

install.packages(setdiff(packages, rownames(installed.packages())))  

library(MASS)
library(e1071)
library(caret)
library(neuralnet)
library(glmnet)
library(mltools)
library(data.table)
library(janitor)
library(corrplot)
library(dplyr)
library(jtools)

ALL <- read.csv(file = "final_partitioned/all.csv")
PROF.PROF <- read.csv(file = "final_partitioned/prof.prof.csv")
PROF.ASC <- read.csv(file = "final_partitioned/prof.asc.csv")
PROF.AST <- read.csv(file = "final_partitioned/prof.ast.csv")
INS <- read.csv(file = "final_partitioned/ins.csv")
FAC <- read.csv(file = "final_partitioned/fac.csv")
GT <- read.csv(file = "final_partitioned/gt.csv")
ALL.I <- read.csv(file = "final_partitioned/all_i.csv")
PROF.PROF.I <- read.csv(file = "final_partitioned/prof.prof_i.csv")
PROF.ASC.I <- read.csv(file = "final_partitioned/prof.asc_i.csv")
PROF.AST.I <- read.csv(file = "final_partitioned/prof.ast_i.csv")
INS.I <- read.csv(file = "final_partitioned/ins_i.csv")
FAC.I <- read.csv(file = "final_partitioned/fac_i.csv")
GT.I <- read.csv(file = "final_partitioned/gt_i.csv")

#####ONE HOT CATEGORICAL#####
ALL$State <- as.factor(ALL$State)
ALL$Institution <- as.factor(ALL$Institution)
ALL$Race <- as.factor(ALL$Race)
ALL$Gender <- as.factor(ALL$Gender)
ALL$Role <- as.factor(ALL$Role)
ALL <- one_hot(as.data.table(ALL))
ALL <- clean_names(ALL)

ALL.I$State <- as.factor(ALL.I$State)
ALL.I$Institution <- as.factor(ALL.I$Institution)
ALL.I$intersection <- as.factor(ALL.I$intersection)
ALL.I$Role <- as.factor(ALL.I$Role)
ALL.I <- one_hot(as.data.table(ALL.I))
ALL.I <- clean_names(ALL.I)

PROF.PROF$State <- as.factor(PROF.PROF$State)
PROF.PROF$Institution <- as.factor(PROF.PROF$Institution)
PROF.PROF$Race <- as.factor(PROF.PROF$Race)
PROF.PROF$Gender <- as.factor(PROF.PROF$Gender)
PROF.PROF <- one_hot(as.data.table(PROF.PROF))
PROF.PROF <- clean_names(PROF.PROF)

PROF.PROF.I$State <- as.factor(PROF.PROF.I$State)
PROF.PROF.I$Institution <- as.factor(PROF.PROF.I$Institution)
PROF.PROF.I$intersection <- as.factor(PROF.PROF.I$intersection)
PROF.PROF.I <- one_hot(as.data.table(PROF.PROF.I))
PROF.PROF.I <- clean_names(PROF.PROF.I)

PROF.ASC$State <- as.factor(PROF.ASC$State)
PROF.ASC$Institution <- as.factor(PROF.ASC$Institution)
PROF.ASC$Race <- as.factor(PROF.ASC$Race)
PROF.ASC$Gender <- as.factor(PROF.ASC$Gender)
PROF.ASC <- one_hot(as.data.table(PROF.ASC))
PROF.ASC <- clean_names(PROF.ASC)

PROF.ASC.I$State <- as.factor(PROF.ASC.I$State)
PROF.ASC.I$Institution <- as.factor(PROF.ASC.I$Institution)
PROF.ASC.I$intersection <- as.factor(PROF.ASC.I$intersection)
PROF.ASC.I <- one_hot(as.data.table(PROF.ASC.I))
PROF.ASC.I <- clean_names(PROF.ASC.I)

PROF.AST$State <- as.factor(PROF.AST$State)
PROF.AST$Institution <- as.factor(PROF.AST$Institution)
PROF.AST$Race <- as.factor(PROF.AST$Race)
PROF.AST$Gender <- as.factor(PROF.AST$Gender)
PROF.AST <- one_hot(as.data.table(PROF.AST))
PROF.AST <- clean_names(PROF.AST)

PROF.AST.I$State <- as.factor(PROF.AST.I$State)
PROF.AST.I$Institution <- as.factor(PROF.AST.I$Institution)
PROF.AST.I$intersection <- as.factor(PROF.AST.I$intersection)
PROF.AST.I <- one_hot(as.data.table(PROF.AST.I))
PROF.AST.I <- clean_names(PROF.AST.I)

FAC$State <- as.factor(FAC$State)
FAC$Institution <- as.factor(FAC$Institution)
FAC$Race <- as.factor(FAC$Race)
FAC$Gender <- as.factor(FAC$Gender)
FAC <- one_hot(as.data.table(FAC))
FAC <- clean_names(FAC)

FAC.I$State <- as.factor(FAC.I$State)
FAC.I$Institution <- as.factor(FAC.I$Institution)
FAC.I$intersection <- as.factor(FAC.I$intersection)
FAC.I <- one_hot(as.data.table(FAC.I))
FAC.I <- clean_names(FAC.I)

INS$State <- as.factor(INS$State)
INS$Institution <- as.factor(INS$Institution)
INS$Race <- as.factor(INS$Race)
INS$Gender <- as.factor(INS$Gender)
INS <- one_hot(as.data.table(INS))
INS <- clean_names(INS)

INS.I$State <- as.factor(INS.I$State)
INS.I$Institution <- as.factor(INS.I$Institution)
INS.I$intersection <- as.factor(INS.I$intersection)
INS.I <- one_hot(as.data.table(INS.I))
INS.I <- clean_names(INS.I)

GT$Title <- as.factor(GT$Title)
GT$Race <- as.factor(GT$Race)
GT$Gender <- as.factor(GT$Gender)
GT <- one_hot(as.data.table(GT))
GT <- clean_names(GT)

GT.I$Title <- as.factor(GT.I$Title)
GT.I$intersection <- as.factor(GT.I$intersection)
GT.I <- one_hot(as.data.table(GT.I))
GT.I <- clean_names(GT.I)

#####BEST MODELS#####

linear.ALL <- lm(salary ~ ., data = ALL)
linear.ALL.I <- lm(salary ~ ., data = ALL.I)
linear.PROF.PROF <- lm(salary ~ ., data = PROF.PROF)
linear.PROF.PROF.I <- lm(salary ~ ., data = PROF.PROF.I)
linear.PROF.ASC <- lm(salary ~ ., data = PROF.ASC)
linear.PROF.ASC.I <- lm(salary ~ ., data = PROF.ASC.I)
linear.PROF.AST <- lm(salary ~ ., data = PROF.AST)
linear.PROF.AST.I <- lm(salary ~ ., data = PROF.AST.I)
linear.INS <- lm(salary ~ ., data = INS)
linear.INS.I <- lm(salary ~ ., data = INS.I)
linear.FAC <- lm(salary ~ ., data=FAC)
linear.FAC.I <- lm(salary ~ ., data=FAC.I)
linear.GT <- lm(salary ~ ., data=GT)
linear.GT.I <- lm(salary ~ ., data=GT.I)

coef.ALL <- data.frame(summary(linear.ALL)$coefficients)
coef.PROF.PROF <- data.frame(summary(linear.PROF.PROF)$coefficients)
coef.PROF.ASC <- data.frame(summary(linear.PROF.ASC)$coefficients)
coef.PROF.AST <- data.frame(summary(linear.PROF.AST)$coefficients)
coef.INS <- data.frame(summary(linear.INS)$coefficients)
coef.FAC <- data.frame(summary(linear.FAC)$coefficients)
coef.GT <- data.frame(summary(linear.GT)$coefficients)

coef.ALL.I <- data.frame(summary(linear.ALL.I)$coefficients)
coef.PROF.PROF.I <- data.frame(summary(linear.PROF.PROF.I)$coefficients)
coef.PROF.ASC.I <- data.frame(summary(linear.PROF.ASC.I)$coefficients)
coef.PROF.AST.I <- data.frame(summary(linear.PROF.AST.I)$coefficients)
coef.INS.I <- data.frame(summary(linear.INS.I)$coefficients)
coef.FAC.I <- data.frame(summary(linear.FAC.I)$coefficients)
coef.GT.I <- data.frame(summary(linear.GT.I)$coefficients)


write.csv(coef.ALL, "model_coef/all.csv")
write.csv(coef.PROF.PROF, "model_coef/prof.prof.csv")
write.csv(coef.PROF.ASC, "model_coef/prof.asc.csv")
write.csv(coef.PROF.AST, "model_coef/prof.ast.csv")
write.csv(coef.FAC, "model_coef/fac.csv")
write.csv(coef.INS, "model_coef/ins.csv")
write.csv(coef.GT, "model_coef/gt.csv")

write.csv(coef.ALL.I, "model_coef/all_i.csv")
write.csv(coef.PROF.PROF.I, "model_coef/prof.prof_i.csv")
write.csv(coef.PROF.ASC.I, "model_coef/prof.asc_i.csv")
write.csv(coef.PROF.AST.I, "model_coef/prof.ast_i.csv")
write.csv(coef.FAC.I, "model_coef/fac_i.csv")
write.csv(coef.INS.I, "model_coef/ins_i.csv")
write.csv(coef.GT.I, "model_coef/gt_i.csv")
